name: bShop
version: 1.2
main: net.bumpier.bshop.BShop
api-version: 1.20
author: bumpier.dev
description: A modern, modular, and high-performance GUI shop plugin.
softdepend: [Vault]
commands:
  shop:
    description: Opens the main shop GUI or performs an admin action.
    usage: /shop [category|reload|multiplier]
    aliases: [bshop, eshop]
permissions:
  bshop.admin.reload:
    description: Allows the user to reload the bShop plugin configuration.
    default: op
  bshop.admin.multiplier.give:
    description: Allows giving temporary multipliers to players.
    default: op
  bshop.admin.multiplier.remove:
    description: Allows removing temporary multipliers from players.
    default: op
  bshop.admin.multiplier.list:
    description: Allows listing all active temporary multipliers.
    default: op
  bshop.admin.multiplier.clear:
    description: Allows clearing all temporary multipliers.
    default: op